SELECT STR.PRJ_CODE,
       STR.PRJ_NAME,
       DT.IMPLEMENT_RANGE,
       DT.PRJ_TARGET,
       DT.PRJ_CONTENT,
       Z_TOTAL_FUND,
       Z_HARDWARE,
       Z_SOFTWARE,
       Z_DEVELOP,
       Z_IMPLEMENT,
       Z_OTHER,
       Y_TOTAL_FUND,
       Y_HARDWARE,
       Y_SOFTWARE,
       Y_DEVELOP,
       Y_IMPLEMENT,
       Y_OTHER,
       TOTAL_FUND,
       CAPITAL_FUND,
       COST_FUND,
       HARDWARE,
       SOFTWARE,
       DEVELOP,
       IMPLEMENT,
       OTHER,
       PRJ_BASIS,
       EXAMINE_SITUATION,
       PRJ_SCORE,
       MEMO,
       DT.DETAIL_ID,
       (CASE WHEN BU.PRJ_CODE IS NULL AND D.PRJ_CODE IS NULL THEN 1 ELSE 0 END) CANEDIT
  FROM PM_STORE STR
  LEFT JOIN PM_ADVICE ADV
    ON STR.PRJ_CODE = ADV.PRJ_CODE
   AND STR.IS_UNI_PROMOTE = '0'
  LEFT JOIN PM_RESEARCH RE
    ON STR.PRJ_CODE = RE.PRJ_CODE
   AND STR.IS_UNI_PROMOTE = '1'
  LEFT JOIN PM_STORE_RPT_DETAIL DT
    ON STR.PRJ_CODE = DT.PRJ_CODE
  LEFT JOIN PM_S_BUDGET B
    ON B.PRJ_CODE = STR.PRJ_CODE
   AND B.DATA_STATUS = 1
  LEFT JOIN (SELECT DISTINCT RPTD.PRJ_CODE FROM PM_ALP_RPT_DETAIL RPTD) D
    ON D.PRJ_CODE = STR.PRJ_CODE
  LEFT JOIN (SELECT DISTINCT PB.PRJ_CODE
    FROM PM_BUILD PB
   WHERE PB.VALID_FLAG = 1) BU
   ON BU.PRJ_CODE = STR.PRJ_CODE
   
