SELECT P1.NAME || '/' || P2.NAME || '/' || P3.NAME,
P3.VALUE
  FROM P_CODE P1
  LEFT JOIN P_CODE P2
    ON P1.VALUE = P2.P_CODE
   AND P1.CODE_TYPE = P2.CODE_TYPE
  INNER JOIN P_CODE P3
    ON P2.VALUE = P3.P_CODE
   AND P2.CODE_TYPE = P3.CODE_TYPE
  WHERE P1.CODE_TYPE = '23000000'
