TRUNCATE TABLE PM_ALP_DHT;
TRUNCATE TABLE PM_ALP_FHT;
TRUNCATE TABLE PM_ALP_RELEASE;
DELETE FROM PM_BUNCH_DETAIL D WHERE NOT EXISTS (SELECT NULL FROM PM_BUNCH B WHERE B.VER_ID IS NULL AND B.BUNCH_ID = D.BUNCH_ID);
DELETE PM_BUNCH B WHERE B.VER_ID IS NOT NULL;
