DELETE FROM PM_ALP_DHT D WHERE EXISTS (SELECT NULL FROM PM_ALP_RELEASE R WHERE R.RPT_YEAR = 2014 AND R.VER_NO = '3' AND R.VER_ID = D.VER_ID AND R.ORG_NO IN (100100,100300));
DELETE FROM PM_ALP_FHT F WHERE EXISTS (SELECT NULL FROM PM_ALP_RELEASE R WHERE R.RPT_YEAR = 2014 AND R.VER_NO = '3' AND R.VER_ID = F.VER_ID AND R.ORG_NO IN (100100,100300));
--项目包永远是完整更新
DELETE FROM PM_BUNCH_DETAIL D WHERE NOT EXISTS (SELECT NULL FROM PM_BUNCH B WHERE B.VER_ID = '3' AND B.BUNCH_YEAR = 2014 AND B.BUNCH_ID = D.BUNCH_ID);
DELETE FROM PM_BUNCH B WHERE B.VER_ID = '3' AND B.BUNCH_YEAR = '2014';
DELETE FROM PM_ALP_RELEASE R WHERE R.VER_NO = '3' AND R.RPT_YEAR = '2014' AND R.ORG_NO IN (100100,100300);
