--从Release表中取得历史资金估算 By HF 20120614
SELECT F1.FUND_ID,D.DETAIL_ID,F1.FUND_TYPE,F1.TOTAL_FUND,F1.CAPITAL_FUND,F1.COST_FUND,F1.SOFT_FUND,F1.HAD_FUND,F1.DEVEP_FUND,F1.PEFM_FUND,F1.OTHER_FUND,
F2.FUND_ID,D.DETAIL_ID,F2.FUND_TYPE,F2.TOTAL_FUND,F2.CAPITAL_FUND,F2.COST_FUND,F2.SOFT_FUND,F2.HAD_FUND,F2.DEVEP_FUND,F2.PEFM_FUND,F2.OTHER_FUND,
F3.FUND_ID,D.DETAIL_ID,F3.FUND_TYPE,F3.TOTAL_FUND,F3.CAPITAL_FUND,F3.COST_FUND,F3.SOFT_FUND,F3.HAD_FUND,F3.DEVEP_FUND,F3.PEFM_FUND,F3.OTHER_FUND,
D.NEXT_INV_FUND
 FROM PM_ALP_DHT D
          LEFT JOIN PM_ALP_RELEASE R
            ON R.VER_ID = D.VER_ID
           AND D.RPT_ID = R.RPT_ID
          LEFT JOIN PM_ALP_FHT F1
            ON D.DETAIL_ID = F1.DETAIL_ID
           AND D.VER_ID = F1.VER_ID
           AND F1.FUND_TYPE = 01
          LEFT JOIN PM_ALP_FHT F2
            ON D.DETAIL_ID = F2.DETAIL_ID
           AND D.VER_ID = F2.VER_ID
           AND F2.FUND_TYPE = 02
          LEFT JOIN PM_ALP_FHT F3
            ON D.DETAIL_ID = F3.DETAIL_ID
           AND D.VER_ID = F3.VER_ID
           AND F3.FUND_TYPE = 03
         WHERE R.RPT_YEAR = 2012
           AND R.VER_NO = 3
           AND D.PRJ_CODE = '711001124245'
