--取出某个单位通过审核的年度计划值列表
  SELECT SUM(FD.TOTAL_FUND),RPT.ORG_NO
       FROM PM_ALP_CREATE CRT, PM_ALP_RPT RPT,PM_BASE_INFO PBI ,
       PM_ALP_RPT_DETAIL DET
        LEFT JOIN PM_ALP_FUND FD ON FD.DETAIL_ID = DET.DETAIL_ID
        AND FD.FUND_TYPE = 03
        WHERE CRT.PLAN_YEAR = 2012
        AND RPT.APP_NO = CRT.APP_NO
        AND DET.RPT_ID = RPT.RPT_ID
        AND PBI.PRJ_CODE = DET.PRJ_CODE
        AND DET.EDIT_TYPE_CODE = 02
        AND RPT.STATUS_CODE = 04
        GROUP BY RPT.ORG_NO
