--年度计划四大类投资汇总表点击查看项目详细（查询当前数据）
SELECT DECODE(B2.BUNCH_ID,NULL,RS.PRJCODE,B2.BUNCH_ID) PRJ_ID,
       DECODE(RS.IS_BUNCH, 1, B2.BUNCH_NAME, INF.PRJ_NAME) PRJNAME,
       C3.NAME YJ,
       C2.NAME EJ,
       C1.NAME SJ,
       ZTRHJ,
       YWCHJ,
       JHHJ,
       D3.NEXT_INV_FUND,
       PS.PRJ_MARK,
       B2.BUNCH_ID,
       '' AS APPNO
  FROM (SELECT DECODE(B.BUNCH_NO, NULL, D.PRJ_CODE, B.BUNCH_NO) PRJCODE,
               DECODE(COUNT(B.BUNCH_NO), 0, 0, 1) IS_BUNCH,
               SUM(F3.TOTAL_FUND) JHHJ,
               SUM(F3.COST_FUND) JHZBJ,
               SUM(F3.CAPITAL_FUND) JHCBJ,
               SUM(F1.TOTAL_FUND) ZTRHJ,
               SUM(F1.COST_FUND) ZTRZBJ,
               SUM(F1.CAPITAL_FUND) ZTRCBJ,
               SUM(F2.TOTAL_FUND) YWCHJ,
               SUM(F2.COST_FUND) YWCZBJ,
               SUM(F2.CAPITAL_FUND) YWCCBJ
          FROM PM_ALP_RPT_DETAIL D
          LEFT JOIN PM_ALP_RPT R
           ON D.RPT_ID = R.RPT_ID
           AND D.EDIT_TYPE_CODE = 02
          LEFT JOIN (SELECT * FROM PM_BUNCH_DETAIL DT WHERE EXISTS (SELECT NULL FROM PM_BUNCH BT WHERE BT.BUNCH_ID = DT.BUNCH_ID AND BT.VER_ID IS NULL)) DB
            ON DB.PRJ_CODE = D.PRJ_CODE
          LEFT JOIN (SELECT * FROM PM_BUNCH BX WHERE BX.VER_ID IS NULL) B
            ON DB.BUNCH_ID = B.BUNCH_ID
           AND B.VER_ID IS NULL
          LEFT JOIN PM_ALP_FUND F1
            ON D.DETAIL_ID = F1.DETAIL_ID
           AND F1.FUND_TYPE = 01
          LEFT JOIN PM_ALP_FUND F2
            ON D.DETAIL_ID = F2.DETAIL_ID
           AND F2.FUND_TYPE = 02
          LEFT JOIN PM_ALP_FUND F3
            ON D.DETAIL_ID = F3.DETAIL_ID
           AND F3.FUND_TYPE = 03
         WHERE R.APP_NO = '120610112650'
               AND D.PF_SORT_CODE = LPAD(1, 2, '0')
               AND R.ORG_NO = '100100'
           --此处输入单位
         GROUP BY DECODE(B.BUNCH_NO, NULL, D.PRJ_CODE, B.BUNCH_NO)) RS
  LEFT JOIN (SELECT * FROM PM_BUNCH BX WHERE BX.VER_ID IS NULL) B2
    ON RS.IS_BUNCH = 1
   AND B2.BUNCH_NO = RS.PRJCODE
--此条连接如果连上RS.IS_BUNCH = 0会导致结果不正常，原因不明
  LEFT JOIN (SELECT * FROM PM_ALP_RPT_DETAIL DL WHERE EXISTS (SELECT NULL FROM PM_ALP_RPT RP WHERE RP.APP_NO = '120610112650' AND DL.RPT_ID = RP.RPT_ID)) D3
    ON RS.PRJCODE = D3.PRJ_CODE
  LEFT JOIN PM_BASE_INFO INF
    ON RS.IS_BUNCH = 0
   AND INF.PRJ_CODE = RS.PRJCODE
   
  LEFT JOIN P_CODE C1
    ON DECODE(D3.PT_SORT_CODE,NULL,B2.PRJ_SORT_CODE||'01',D3.PT_SORT_CODE) = C1.VALUE
   AND C1.CODE_TYPE = '23000000'
  LEFT JOIN P_CODE C2
    ON C1.P_CODE = C2.VALUE
   AND C2.CODE_TYPE = '23000000'
  LEFT JOIN P_CODE C3
    ON C2.P_CODE = C3.VALUE
   AND C3.CODE_TYPE = '23000000'
   
  LEFT JOIN PM_STORE PS
    ON RS.PRJCODE = PS.PRJ_CODE
   WHERE DECODE(RS.IS_BUNCH, 1, B2.BUNCH_NAME, INF.PRJ_NAME) LIKE '%总部%'
   --WHERE DECODE(D3.PT_SORT_CODE,NULL,B2.PRJ_SORT_CODE||'01',D3.PT_SORT_CODE) 888888888888888888888888888888
   ORDER BY C3.VALUE,C2.VALUE,C1.VALUE
