-- 合并时需要的值--
-- 1、要合并的年份: PLAN_YEAR               
-- 2、要合并到哪个流程，APP_NO              

-----------具体操作过程--------------------------------------
---------------------------以2014年合并测试
-- 一、 查看有那些单位要发起新的流程
SELECT DISTINCT OLDRPT.ORG_NO, OLDRPT.ORG_NAME, OLDCRT.PLAN_YEAR 
FROM PM_ALP_CREATE OLDCRT, PM_ALP_RPT OLDRPT
WHERE OLDCRT.PLAN_YEAR='2014' AND OLDRPT.APP_NO = OLDCRT.APP_NO 

-- 二、创建新流程，并将流程跑完，并所有的单位审核通过（测试时APP_NO = 120410115161 ）

-- 三、合并数据
-- 3.1  构造表（原上报ID，要更新成的上报ID， 单位编号）
SELECT OLDRPT.RPT_ID ORPTID, NEWRPT.RPT_ID NRPTID, NEWRPT.ORG_NO 
FROM PM_ALP_RPT OLDRPT ,PM_ALP_CREATE OLDCRT ,PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'

-- 3.2 将 PM_ALP_VHT（年度计划版本表）中原来的RPT_ID 更新为新的
/* --  查询那些数据在更新
SELECT * FROM PM_ALP_VHT VHT, PM_ALP_CREATE CRT 
WHERE VHT.APP_NO = CRT.APP_NO AND CRT.PLAN_YEAR ='2014'
AND CRT.APP_NO !='120410115161'
ORDER BY VHT.ORG_NO*/

UPDATE PM_ALP_VHT VHT SET VHT.RPT_ID = (
  SELECT NEWRPT.RPT_ID
FROM PM_ALP_RPT OLDRPT ,PM_ALP_CREATE OLDCRT ,PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'
AND OLDRPT.RPT_ID = VHT.RPT_ID
AND NEWRPT.ORG_NO = VHT.ORG_NO
)
WHERE EXISTS (SELECT 1 
FROM PM_ALP_RPT OLDRPT ,PM_ALP_CREATE OLDCRT ,PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'
AND OLDRPT.RPT_ID = VHT.RPT_ID
AND NEWRPT.ORG_NO = VHT.ORG_NO) 
AND VHT.APP_NO != '120410115161'


-- 3.3 更新PM_ALP_DHT（版本明细表）
UPDATE PM_ALP_DHT DHT SET DHT.RPT_ID = (SELECT VHT.RPT_ID FROM PM_ALP_VHT VHT WHERE VHT.VER_ID = DHT.VER_ID)



-- 3.4 更新PM_ALP_RPT_DETAIL(计划编制明细)
/* --查看要更新的数据
SELECT DET.* FROM PM_ALP_CREATE CRT , PM_ALP_RPT RPT, PM_ALP_RPT_DETAIL DET
WHERE CRT.PLAN_YEAR ='2014' AND RPT.APP_NO = CRT.APP_NO AND DET.RPT_ID = RPT.RPT_ID
AND CRT.APP_NO != '120410115161'
*/

UPDATE PM_ALP_RPT_DETAIL DET SET DET.RPT_ID = (
SELECT NEWRPT.RPT_ID NRPTID
FROM PM_ALP_RPT OLDRPT ,PM_ALP_CREATE OLDCRT ,PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'
AND DET.RPT_ID = OLDRPT.RPT_ID
)
WHERE EXISTS (
SELECT 1
FROM PM_ALP_RPT OLDRPT, PM_ALP_CREATE OLDCRT, PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'
AND DET.RPT_ID = OLDRPT.RPT_ID
)


---------------------------------------------------------
-- 四、删除多余数据
-- 4.1 删除PM_ALP_RPT（年度计划编制）
DELETE FROM PM_ALP_RPT RPT 
WHERE EXISTS (
SELECT 1
FROM PM_ALP_RPT OLDRPT, PM_ALP_CREATE OLDCRT, PM_ALP_RPT NEWRPT
WHERE OLDRPT.ORG_NO = NEWRPT.ORG_NO 
AND OLDRPT.APP_NO =OLDCRT.APP_NO 
AND OLDCRT.PLAN_YEAR='2014'
AND NEWRPT.APP_NO ='120410115161'
AND OLDRPT.APP_NO !='120410115161'
AND RPT.RPT_ID = OLDRPT.RPT_ID
)

-- 4.2 删除PM_ALP_CREATE（年度计划发起）
DELETE FROM PM_ALP_CREATE CRT 
WHERE CRT.APP_NO !=  '120410115161' AND crt.plan_year ='2014'


-- 档案表
UPDATE PM_DOC  DC SET DC.APP_NO ='NEWAPPNO' WHERE DC.APP_NO ='OLDDAPPNO' 

-- 审核信息
UPDATE P_APPROVE AP SET AP.APP_NO ='NEWAPPNO' WHERE AP.APP_NO ='OLDDAPPNO'
