
INSERT INTO PM_BUNCH_DETAIL
  (DETAIL_ID, BUNCH_ID, PRJ_CODE)
  SELECT SYS_GUID(), B2.BUNCH_ID, BD.PRJ_CODE
    FROM (SELECT D.BUNCH_ID, D.PRJ_CODE, B.BUNCH_NAME
            FROM PM_BUNCH_DETAIL D
            LEFT JOIN PM_BUNCH B
              ON B.BUNCH_ID = D.BUNCH_ID
             AND B.VER_ID IS NULL) BD
    LEFT JOIN PM_BUNCH B2
      ON BD.BUNCH_NAME = B2.BUNCH_NAME
     AND B2.VER_ID = '1.1' AND B2.BUNCH_YEAR = '2012'
