INSERT INTO PM_ALP_DHT
  (DET_VER_ID,
   VER_ID,
   DETAIL_ID,
   RPT_ID,
   PRJ_CODE,
   EDIT_TYPE_CODE,
   PF_SORT_CODE,
   PT_SORT_CODE,
   INVE_EXP,
   NEXT_INV_FUND,
   REMARK)
  SELECT X.GID AS DET_VER_ID,
         R.VER_ID,
         D.DETAIL_ID,
         D.RPT_ID,
         D.PRJ_CODE,
         D.EDIT_TYPE_CODE,
         D.PF_SORT_CODE,
         D.PT_SORT_CODE,
         D.INVE_EXP,
         D.NEXT_INV_FUND,
         D.Remark
    FROM PM_ALP_RPT_DETAIL D LEFT JOIN PM_ALP_RELEASE R ON R.RPT_ID = D.RPT_ID,(SELECT SYS_GUID() AS GID FROM DUAL) X
    WHERE EXISTS (SELECT NULL FROM PM_ALP_RPT R WHERE R.APP_NO = (SELECT MAX(C.APP_NO) FROM PM_ALP_CREATE C WHERE C.PLAN_YEAR = '2012') AND R.RPT_ID = D.RPT_ID AND R.STATUS_CODE = '04')
    AND R.VER_NO = '1.1' AND R.RPT_YEAR = '2012'
