SELECT T.PRJ_CODE--, T.PRJ_NAME, V.ISBUNCH
  FROM PM_IMR_PROJECT T
  LEFT JOIN PM_IMR_INFO I
    ON T.RPT_YEAR = I.RPT_YEAR
   AND T.RPT_MONTH = I.RPT_MONTH
  LEFT JOIN V_PM_ALP_FINAL_PROJECT V
    ON T.PRJ_CODE = V.BUNCH_NO
 WHERE I.APP_NO = 120410114704
   AND V.ORG_NO = 100100
   AND V.ISBUNCH = 1;
